### ISSUE TITLE
monitor goes to standby after booting successfully

### ISSUE THREAD

**Issue by rakewell** [roederja/asus-rog-strix-b460I-hackintosh#1]
Hi, thanks for your guide, it's been very helpful.

The system boots fine but the monitor goes to standby after the apple logo appears. If I unplug the hdmi cable (or display port) and then plug it back in to the computer, the apple login screen appears and I can use the mac flawlessly. Is there any way around this?

**Comment by roederja** [comment]
What kind of GPU do you have?

**Comment by chainometry** [comment]
Integrated:
Intel Core i5 10500 (Base:3.10GHz, Turbo:4.50GHz / 12MB / LGA1200 / 6 Core / 65W / UHD 630 / Comet Lake-S)

**Comment by roederja** [comment]
I assume you didn't use the AMD Radeon specific settings from my config? I didn't have any issues with only the integrated GPU.

**Comment by chainometry** [comment]
Ahh, you pointed me in the right direction. I had only initially omitted the SSDT-RX5700XT file but after your comment I removed the agdpmod=pikera boot arg and the display stayed on after the apple logo showing the login screen. Many thanks for your help on this.
