### ISSUE TITLE
FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext not needed anymore

### ISSUE THREAD

**Issue by dmikhalsky** [roederja/asus-rog-strix-b460I-hackintosh#13]
Good news, guys,

As of ver 1.7.2 AppleALC.kext supports Intel 400-series HD audio (HDMI audio) so we don't need both FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext anymore.

Two benefits from this:
a) less kexts, less mess
b) trouble-free upgrade to Monterey as Fake_xxx kexts are NOT compatible with Monterey

Needless to say, I tested Fake-less config on my machine and it works like a breeze.

**Comment by roederja** [comment]
What changes did you have to make? Just removing the Fake kexts and using the latest AppleALC does not work for me.

**Comment by roederja** [comment]
Figured it out. I'll update the readme.
