### ISSUE TITLE
Need some help pls...

### ISSUE THREAD

**Issue by hardbone12** [roederja/asus-rog-strix-b460I-hackintosh#2]
Thanks for your share.

My build:
CPU: i7 10700

GPU: Intel UHD Graphics 630

RAM:  CORSAIR LPX DDR4 3000 32G (16Gx2)

MB: ROG-STRIX-B460-I (BIOS Ver: latest 0707)

Screen(s) - DisplayPort

M2: Western Digital SN750 500G

Wifi/BT Card: Intel AX200(Wi-Fi 6)

BOOT: OpenCore 0.6.2 with Catalina 15.5.5 Installer

I'm stuck in a issue:
The stick boot and install to the local drive looks fine.
But perform the second stage of installation when after install reboot, the progress bar is about halfway and "About 8 minutes remaining", the system restart suddenly, and again...again...

The config.plist i'm using:
[config.plist](https://gist.github.com/hardbone12/6932a05dc65893518bf2ad87d50b3a67)

**Comment by roederja** [comment]
Your config.plist is significantly different than mine with lots of additional kexts. Also you are using an outdated OS X version. I'd try without all the extra kexts and a recent OS X version and see if you can get it to install/boot. Then you can experiment with adding the extra kexts back.

**Comment by hardbone12** [comment]
yep, I haven't to replace the wifi card in time, so.. add some kexts for intel ax200, also i'll try to remove these extra kexts.

have you tried oc 0.6.3 latest version with your config before?

**Comment by roederja** [comment]
No, not yet. I don't think there are any relevant changes if you aren't running BigSur.

**Comment by hardbone12** [comment]
yes, i agree with you. and I wonder Is there any way to let installer output some debug or error info of the installation process?

**Comment by roederja** [comment]
If you follow the Dortania guide it will tell you to enable all sorts of debug output. My config is the final version with that disabled again.

**Comment by Caoyvming** [comment]
> yes, i agree with you. and I wonder Is there any way to let installer output some debug or error info of the installation process?

During the installing process, actually, you have entered the macOS, so the OpenCore may cant capture the error info. I think so...

**Comment by Caoyvming** [comment]
> Thanks for your share.
> 
> My build:
> CPU: i7 10700
> 
> GPU: Intel UHD Graphics 630
> 
> RAM: CORSAIR LPX DDR4 3000 32G (16Gx2)
> 
> MB: ROG-STRIX-B460-I (BIOS Ver: latest 0707)
> 
> Screen(s) - DisplayPort
> 
> M2: Western Digital SN750 500G
> 
> Wifi/BT Card: Intel AX200(Wi-Fi 6)
> 
> BOOT: OpenCore 0.6.2 with Catalina 15.5.5 Installer
> 
> I'm stuck in a issue:
> The stick boot and install to the local drive looks fine.
> But perform the second stage of installation when after install reboot, the progress bar is about halfway and "About 8 minutes remaining", the system restart suddenly, and again...again...
> 
> The config.plist i'm using:
> [config.plist](https://gist.github.com/hardbone12/6932a05dc65893518bf2ad87d50b3a67)

The suddenly reboot during the installing process is very normal! Make sure you choose the right entrance in OC (it can choose correctly by itself, and the name likes called 'xxxinstaller', i cant remember.) If this cant fix your problem, you can just rebuild your EFI files with the author's repository step by step.

**Comment by hardbone12** [comment]
@Caoyvming i'm using owner's repo, and now im trying update the OSX installer version, clean up some kexts, but it doesn't look better :-(

Could you share your folder with me, I want to figure out it's a hardware or other problem. Thanks a lot 
hardbone16@gmail.com

**Comment by Caoyvming** [comment]
看你名字，帝国公民？



发自我的iPhone


------------------ Original ------------------

**Comment by Caoyvming** [comment]
> Thanks for your share.
> 
> My build:
> CPU: i7 10700
> 
> GPU: Intel UHD Graphics 630
> 
> RAM: CORSAIR LPX DDR4 3000 32G (16Gx2)
> 
> MB: ROG-STRIX-B460-I (BIOS Ver: latest 0707)
> 
> Screen(s) - DisplayPort
> 
> M2: Western Digital SN750 500G
> 
> Wifi/BT Card: Intel AX200(Wi-Fi 6)
> 
> BOOT: OpenCore 0.6.2 with Catalina 15.5.5 Installer
> 
> I'm stuck in a issue:
> The stick boot and install to the local drive looks fine.
> But perform the second stage of installation when after install reboot, the progress bar is about halfway and "About 8 minutes remaining", the system restart suddenly, and again...again...
> 
> The config.plist i'm using:
> [config.plist](https://gist.github.com/hardbone12/6932a05dc65893518bf2ad87d50b3a67)
I have sent my EFI to your email.
And i think the problem is:  perhaps you used the front USB ports to install macOS.
Try to use the back USB ports, because the owners repo does't map the front USB ports.

**Comment by hardbone12** [comment]
problem resolved. close this issue
