### ISSUE TITLE
After complete my installtion, I found that there are too many "??" in "PCIe" of "hackintool.app". Does it matter?

### ISSUE THREAD

**Issue by Caoyvming** [roederja/asus-rog-strix-b460I-hackintosh#3]
My motherboard is also the ASUS-B460i with Intel 10700. So I use your repository to build my EFI files.

There is the screenshot:
<img width="1188" alt="Screen Shot 2020-11-08 at 9 14 23 PM" src="https://user-images.githubusercontent.com/28008315/98465949-646e5580-2207-11eb-918a-b593e8d84043.png">
AND, Can you find your Graphics' info in iStates.app? 
<img width="256" alt="Screen Shot 2020-11-08 at 9 15 01 PM" src="https://user-images.githubusercontent.com/28008315/98465958-7819bc00-2207-11eb-93e1-9c0b1f57a9f1.png">

**Comment by roederja** [comment]
Don't think the question marks matter - mine is the same. I also can't get temperature readings from my Navi GPU - but that is a known issue.
